name: build

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build_type: ['Release']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Linux system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libgl-dev
        
    - name: Install Conan
      run: pip3 install conan
          
    - name: Install conan dependencies Linux
      if: runner.os == 'Linux'
      # Use sudo because of some needed system package
      run: sudo PYTHONPATH=~/.local/lib/python3.8/site-packages env "PATH=$PATH" conan install -b missing -s build_type=${{ matrix.build_type }} -c tools.system.package_manager:mode=install --no-imports .
        
    - name: Install conan dependencies Windows
      if: runner.os == 'Windows'
      run: conan install -b missing -s build_type=${{ matrix.build_type }} --no-imports .

    - name: Configure
      run: |
        conan install -if ${{github.workspace}}/build -s build_type=${{ matrix.build_type }} .
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build_type }}   
