name: build

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build_type: ['Release']
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Linux system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libgl-dev xorg-dev
        
    - name: Install Conan
      run: pip3 install conan          
        
    - name: Run Conan
      run: conan install -if ${{github.workspace}}/build -b missing -s build_type=${{ matrix.build_type }} .

    - name: Configure
      run: cmake -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build_type }}   
